### ISSUE TITLE
Transition.render(): A valid ReactComponent must be returned.

### ISSUE THREAD

**Issue by vinceprofeta** [souporserious/react-motion-ui-pack#39] opened 2016-02-26 18:01 UTC
@souporserious 
I am getting this error in safari, and cant figure out whats going on?

Invariant Violation: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.

`<Transition key="key-2"
          component={false}
          enter={{
            opacity: 1,
            translateY: spring(0, [210, 14])
          }}
          leave={{
            opacity: 0,
            translateY: spring(50, [210, 14])
          }}>
            <div></div>
          </Transition>
`

**Comment by souporserious** [comment] 2016-02-26 19:45
This sounds like it could be an error on your end. Can you post a gist or snippet of the code you are using please?

**Comment by frederickfogerty** [comment] 2016-02-26 19:58
Stab in the dark, but sounds like you’re passing an instantiated React Element (i.e. `component={<div />}`) rather than passing a component type (i.e. `component={div}`). We should probably support this though.

**Comment by souporserious** [comment] 2016-02-26 19:59
@frederickfogerty could this be related to https://github.com/souporserious/react-motion-ui-pack/issues/36? I agree it should be supported.

**Comment by frederickfogerty** [comment] 2016-02-26 20:53
Similar, but @vinceprofeta is getting an error, #36 is just a warning

**Comment by vinceprofeta** [comment] 2016-02-26 23:06
The code above was throwing an error in safari. It seems to be working in all other browsers. It may be a webpack compilation error? I'm not wrapping a component so the instantiation issue shouldn't be the case. Is the above code working for you all in safari? I have been out today and will take a deeper dive once I get back

**Comment by souporserious** [comment] 2016-04-13 04:29
@vinceprofeta I just cut a new release, can you please let me know if you are still getting this issue?

**Comment by souporserious** [comment] 2016-05-19 02:30
Closing this for now, cannot reproduce it on my end. Please let me know if this is still occurring.

**Closed as completed by souporserious** 2016-05-19 02:30 UTC
